name: layrz_theme_example
description: layrz_theme_example
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296

  go_router: ^12.1.1
  vxstate: ^2.3.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  flutter_dotenv: ^5.1.0
  flutter_map: ^6.1.0
  flutter_map_animations: any
  layrz_theme:
    path: ../

  layrz_models: ">=2.1.0 <3.0.0"

dependency_overrides:
  http: ^1.0.0
  permission_handler_html:
    git:
      url: https://github.com/raldhafiri/flutter-permission-handler.git
      ref: main
      path: permission_handler_html
  # layrz_models:
  #   path: ../../layrz_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
