name: layrz_theme_example
description: layrz_theme_example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  layrz_models: ^2.0.0
  go_router: ^9.0.3
  vxstate: ^2.3.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  dart_snippet_view: ^0.0.1
  layrz_theme:
    path: ../

dependency_overrides:
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/