image: registry.gitlab.com/goldenm-software/layrz/docker-containers/flutter-web-builder:flutter-3.10.5

stages:
  - deploy
  - pages

deploy:
  stage: deploy

  before_script:
    - gcloud auth activate-service-account --key-file=$PUB_TOKEN
    - gcloud auth print-identity-token --audiences=https://pub.dev | dart pub token add https://pub.dev

  script:
    - dart pub publish -f

  after_script:
    - dart pub token remove https://pub.dev

  tags:
    - saas-linux-small-amd64

  # Add the rule to, if the NOPUB is present in the commit message, do not publish
  # Otherwise, if the commit is from the main branch, publish
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /NOPUB/ 
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
      when: always

pages:
  stage: pages

  before_script:
    - cd $CI_PROJECT_DIR/example
    - flutter clean
    - cd ..
    - flutter clean
    - flutter pub get

  script:
    - cd $CI_PROJECT_DIR/example
    - flutter build web
    - mv build/web $CI_PROJECT_DIR/public

  tags:
    - saas-linux-small-amd64

  only:
    - main
    - development

  artifacts:
    paths:
      - public
