name: layrz_theme
description: Layrz standard theme library for Flutter, based on Material You (Material 3).
version: "4.0.21"
repository: https://gitlab.com/goldenm-software/layrz/flutter-components/layrz_theme

topics:
  - flutter
  - layrz
  - material-design
  - material-3
  - goldenm

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  file: ">=6.1.4 <8.0.0"
  shared_preferences: ">=2.1.0 <2.2.0"
  material_design_icons_flutter: ">=7.0.7296"
  google_fonts: ">=5.1.0 <6.0.0"
  file_picker: ">=5.3.2 <6.0.0"
  mime: ">=1.0.0 <2.0.0"
  flex_color_picker: ">=3.2.0 <4.0.0"
  confetti: ">=0.7.0 <1.0.0"
  pointer_interceptor: ">=0.9.3+4 <1.0.0"
  collection: ">=1.17.1 <2.0.0"
  emojis: ">=0.9.9 <1.0.0"
  get_it: ">=7.6.0 <8.0.0"
  humanize_duration: ">=0.0.1+1 <1.0.0"
  flutter_highlight: ">=0.7.0 <1.0.0"
  highlight: ">=0.7.0 <1.0.0"
  code_text_field: ">=1.1.0 <2.0.0"
  layrz_models: ">=2.0.0 <3.0.0"
  # file_saver: ">=0.2.0 <0.3.0"
  path_provider: ">=2.0.15 <3.0.0"
  permission_handler: ">=10.4.1 <11.0.0"
  document_file_save_plus: ">=2.0.0 <3.0.0"
  flutter_svg: ">=2.0.7 <3.0.0"
  simple_shadow: ">=0.3.1 <0.4.0"

dependency_overrides:
  http: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0 <2.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/layo/
