name: layrz_theme
description: Layrz standard theme library for Flutter, based on Material You (Material 3).
version: "6.0.4"
homepage: https://theme.layrz.com
repository: https://github.com/goldenm-software/layrz_theme

topics:
  - flutter
  - layrz
  - material-design
  - material-3
  - goldenm

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  file: ">=6.1.4 <8.0.0"
  material_design_icons_flutter: ">=7.0.7296"
  google_fonts: ">=6.2.1 <7.0.0"
  mime: ">=1.0.0 <2.0.0"
  flex_color_picker: ">=3.5.0 <4.0.0"
  collection: ">=1.18.0 <2.0.0"
  emojis: ">=0.9.9 <1.0.0"
  path_provider: ">=2.1.3 <3.0.0"
  file_picker: ">=8.0.3 <9.0.0"
  permission_handler: ">=11.3.1 <12.0.0"
  flutter_svg: ">=2.0.10+1 <3.0.0"
  simple_shadow: ">=0.3.1 <0.4.0"
  intl: ">=0.19.0 <1.0.0"
  latlong2: ">=0.9.1 <1.0.0"
  shared_preferences: ">=2.2.3 <3.0.0"
  http: ">=1.2.1 <2.0.0"
  layrz_models: ">=3.0.0 <4.0.0"
  pointer_interceptor: ">=0.10.1+1 <1.0.0"
  two_dimensional_scrollables: ">=0.3.1 <1.0.0"
  sync_scroll_controller: ">=1.0.1 <2.0.0"
  web: ">=0.5.1 <1.0.0"

  # Flutter Map
  flutter_map: ">=6.2.0 <7.0.0"
  flutter_map_cancellable_tile_provider: ">=2.0.0 <3.0.0"

  # Code editor
  flutter_highlight: ">=0.7.0 <1.0.0"
  highlight: ">=0.7.0 <1.0.0"
  code_text_field: ">=1.1.0 <2.0.0"
  url_launcher: ">=6.2.6 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <5.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/layo/
    - assets/testimages/

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
