name: layrz_theme
description: Layrz standard theme library for Flutter, based on Material You (Material 3).
version: "4.3.27"
repository: https://github.com/goldenm-software/layrz_theme

topics:
  - flutter
  - layrz
  - material-design
  - material-3
  - goldenm

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  file: ">=6.1.4 <8.0.0"
  material_design_icons_flutter: ">=7.0.7296"
  google_fonts: ">=6.1.0 <7.0.0"
  file_picker: ">=6.1.1 <7.0.0"
  mime: ">=1.0.0 <2.0.0"
  flex_color_picker: ">=3.3.0 <4.0.0"
  collection: ">=1.17.1 <2.0.0"
  emojis: ">=0.9.9 <1.0.0"
  path_provider: ">=2.0.15 <3.0.0"
  permission_handler: ">=10.4.1 <11.0.0"
  flutter_svg: ">=2.0.7 <3.0.0"
  simple_shadow: ">=0.3.1 <0.4.0"
  intl: ">=0.18.0 <1.0.0"
  flutter_map: ">=6.0.0 <7.0.0"
  latlong2: ">=0.9.0 <1.0.0"
  shared_preferences: ">=2.0.13 <3.0.0"
  http: ">=1.0.0 <2.0.0"
  flutter_map_cancellable_tile_provider: ">=2.0.0 <3.0.0"
  layrz_models: ">=2.1.0 <3.0.0"
  flutter_highlight: ">=0.7.0 <1.0.0"
  highlight: ">=0.7.0 <1.0.0"
  flutter_code_editor: ">=0.3.1 <0.4.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0"

# dependency_overrides:
#   layrz_models:
#     path: ../layrz_models

flutter:
  uses-material-design: true
  assets:
    - assets/layo/
    - assets/testimages/

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
