name: Publish to pub.dev

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goldenm-software/flutter-web-builder:3.13.5
      options: --user root
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate
        run: |
          echo "${{ secrets.LAYRZ_PUB_TOKEN }}" > secrets.json
          gcloud auth activate-service-account --key-file=secrets.json
          gcloud auth print-identity-token --audiences=https://pub.dev | dart pub token add https://pub.dev
      
      - name: Publish
        run: |
          flutter pub publish --force
      
      - name: Cleanup
        run: |
          rm secrets.json
          dart pub token remove https://pub.dev

