name: Publish to pub.dev

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        with:
          credential: ${{ secrets.PUB_TOKEN }}
          flutter_package: true
          skip_test: true
          dry_run: true
